export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS';
export const ACTION_PROFILE_SUCCESS = 'ACTION_PROFILE_SUCCESS';
export const ACTION_GET_LIST = 'ACTION_GET_LIST';
export const ACTION_GET_LIST_CATEGORY = 'ACTION_GET_LIST_CATEGORY';
export const GET_LIST_ITEM_CATEGORY = 'GET_LIST_ITEM_CATEGORY';
export const ACTION_GET_LIST_COOKERS = 'ACTION_GET_LIST_COOKERS';